language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_deploy:
  - npm run prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  github_url: https://hamidraza.github.io/zcui-vue-pwa/
  on:
    branch: master

